services:
  api:
    container_name: SyncBeatAPI
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - GIN_MODE=${GIN_MODE}
    depends_on:
      - db
    networks:
      - sync_beat-network

  db:
    image: postgres:15
    container_name: SyncBeatDB
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - sync_beat_db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - sync_beat-network

volumes:
  sync_beat_db_data:

networks:
  sync_beat-network:
    driver: bridge